import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'tables.dart';

part 'database.g.dart';

@DriftDatabase(tables: [Recipes, RecipeIngredients, RecipeSteps])
// _$ --> class generated by drift that contains all SQL traffic
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super (_openConnection());

  @override
  int get schemaVersion => 1;

  /* Queries */

  //Get all recipes, newest first
  //Stream gets continuous stream of results whenever the recipes table changes
  Stream<List<Recipe>> watchAllRecipes() {
    return (select(recipes)..orderBy([(r) => OrderingTerm.desc(r.createdAt)])).watch();
  } // watchAllRecipes

  // Get ingredients of the recipe
  //Stream gets continuous stream of results whenever the recipes table changes
  Stream<List<RecipeIngredient>> watchIngredientsForRecipe(int recipeId){
    return (select(recipeIngredients)..where((i) => i.recipeId.equals(recipeId))).watch();
  } //watchIngredientsForRecipe

  // Get steps of the recipe
  //Stream gets continuous stream of results whenever the recipes table changes
  Stream<List<RecipeStep>> watchStespsForRecipe(int recipeId) {
    return (select(recipeSteps)..where((s) => s.recipeId.equals(recipeId))
    ..orderBy([(s) => OrderingTerm.asc(s.stepNumber)])).watch();
  } //watchStespsForRecipe

  Future<int> addRecipe(RecipesCompanion entry){
    return into(recipes).insert(entry);
  } //addRecipe

  Future<void> deleteRecipe(int id) {
    return (delete(recipes)..where((r) => r.id.equals(id))).go();
  } //deleteRecipe

} // AppDatabase


/* database file is saved to devices own app data */
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'recipebook.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}