import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'tables.dart';

part 'database.g.dart';

@DriftDatabase(tables: [Recipes])
// _$ --> class generated by drift that contains all SQL traffic
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super (_openConnection());

  @override
  int get schemaVersion => 1;
} // AppDatabase

/* database file is saved to devices own app data */
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'recipebook.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}